Allen/swap req util
EdgeApp/edge-swap-server pull request #10
Opened 2021-07-28 18:34 UTC by algtan

Added a utility function that creates a swap request. Also created unit testing for it.

2021-07-28 20:08 UTC, LPeterson18 commented on src/utils/swapQuotes.ts
> +    1000000
I would recommend using a constant for this number (maybe for the 0 and 1 as well).  As it is, it is a little unclear what the number means or represents.

2021-07-28 20:11 UTC, LPeterson18 commented
I only had one comment. Reassigning to Allen

2021-07-29 03:00 UTC, thehobbit85 commented
/rebase-autosquash

2021-07-29 03:02 UTC, thehobbit85 requested changes
See comment

2021-07-29 03:02 UTC, thehobbit85 commented on src/utils/swapQuotes.ts
> +export const createFromSwapRequest = (
Instead of "regular" function this should be a cleaner.
I'll show you tomorrow what I mean.

2021-07-29 22:38 UTC, LPeterson18 commented
Changes look good to me.

2021-07-31 00:25 UTC, thehobbit85 commented
/rebase-autosquash

2021-07-31 00:25 UTC, merged